title                : "Blahaj Research Institute"
description          : "The Blahaj Research Institute for Transgender Research. Creator of masterdoc.info. Lead by @skymochi64." 
locale               : "en_US"
image                : "https://www.masterdoc.info/assets/images/PFP_V1.png"

keywords:
  - Trans
  - Research
  - Blahaj
  - SkyMochi64
tags:
  - Trans
  - Blahaj
  - Research

encoding             : "utf-8"

author:
  name               : "Blahaj Research Institute"
  avatar             : "https://www.masterdoc.info/assets/images/PFP_V1.png"